# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.info_centralwidget = QtWidgets.QWidget(MainWindow)
        self.info_centralwidget.setObjectName("info_centralwidget")
        self.info_background = QtWidgets.QLabel(self.info_centralwidget)
        self.info_background.setGeometry(QtCore.QRect(0, 0, 700, 600))
        self.info_background.setText("")
        self.info_background.setPixmap(QtGui.QPixmap("info.jpg"))
        self.info_background.setObjectName("info_background")
        self.pushButton = QtWidgets.QPushButton(self.info_centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 500, 150, 70))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.488636, x2:1, y2:0.494318, stop:0 rgba(219, 217, 168, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.info_text = QtWidgets.QLabel(self.info_centralwidget)
        self.info_text.setGeometry(QtCore.QRect(80, 30, 570, 180))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.info_text.setFont(font)
        self.info_text.setObjectName("info_text")
        self.wall_color = QtWidgets.QLabel(self.info_centralwidget)
        self.wall_color.setGeometry(QtCore.QRect(80, 210, 520, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.wall_color.setFont(font)
        self.wall_color.setStyleSheet("background-color: rgb(47, 79, 79);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.wall_color.setObjectName("wall_color")
        self.decrease_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.decrease_colour.setGeometry(QtCore.QRect(80, 330, 520, 40))
        self.decrease_colour.setFont(font)
        self.decrease_colour.setStyleSheet("background-color: rgb(140, 23, 120);\n"
"color: rgb(255, 255, 255);")
        self.decrease_colour.setObjectName("decrease_colour")
        self.default_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.default_colour.setGeometry(QtCore.QRect(80, 290, 520, 40))
        self.default_colour.setFont(font)
        self.default_colour.setStyleSheet("background-color: rgb(239, 211, 52);")
        self.default_colour.setObjectName("default_colour")
        self.portal_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.portal_colour.setGeometry(QtCore.QRect(80, 250, 520, 40))
        self.portal_colour.setFont(font)
        self.portal_colour.setStyleSheet("background-color: rgb(227, 187, 242);")
        self.portal_colour.setObjectName("portal_colour")
        self.bonus_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.bonus_colour.setGeometry(QtCore.QRect(80, 450, 520, 40))
        self.bonus_colour.setFont(font)
        self.bonus_colour.setStyleSheet("background-color: rgb(237, 72, 48);")
        self.bonus_colour.setObjectName("bonus_colour")
        self.fast_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.fast_colour.setGeometry(QtCore.QRect(80, 410, 520, 40))
        self.fast_colour.setFont(font)
        self.fast_colour.setStyleSheet("background-color: rgb(50, 18, 122);\n"
"color: rgb(255, 255, 255);")
        self.fast_colour.setObjectName("fast_colour")
        self.slow_colour = QtWidgets.QLabel(self.info_centralwidget)
        self.slow_colour.setGeometry(QtCore.QRect(80, 370, 520, 40))
        self.slow_colour.setFont(font)
        self.slow_colour.setStyleSheet("background-color: rgb(0, 197, 205);")
        self.slow_colour.setObjectName("slow_colour")
        MainWindow.setCentralWidget(self.info_centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.info_text.setText(_translate("MainWindow", "<html><head/><body><p>Управление змейкой происходит с помощью стрелок</p><p>Q - сохранить игру</p><p>W - выйти из игры </p><p>После запуска игры щелкните мышкой по игровому полю</p><p>Обозначения:</p><p><br/></p></body></html>"))
        self.wall_color.setText(_translate("MainWindow", "- преграда"))
        self.decrease_colour.setText(_translate("MainWindow", "- еда уменьшающая змейку"))
        self.default_colour.setText(_translate("MainWindow", "- стандартная еда"))
        self.portal_colour.setText(_translate("MainWindow", "- портал"))
        self.bonus_colour.setText(_translate("MainWindow", "- еда с бонусными очками"))
        self.fast_colour.setText(_translate("MainWindow", "- еда увеличивающая скорость"))
        self.slow_colour.setText(_translate("MainWindow", "- еда уменьшающая скорость"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
