# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        MainWindow.setStyleSheet("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.board = QtWidgets.QLabel(self.centralwidget)
        self.board.setGeometry(QtCore.QRect(0, 460, 700, 140))
        self.board.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 255, 255, 123), stop:1 rgba(255, 255, 255, 255));")
        self.board.setText("")
        self.board.setPixmap(QtGui.QPixmap("board.png"))
        self.board.setObjectName("board")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 700, 460))
        self.background.setText("")
        self.background.setTextFormat(QtCore.Qt.PlainText)
        self.background.setPixmap(QtGui.QPixmap("Background.jpg"))
        self.background.setObjectName("background")
        self.text_level = QtWidgets.QLabel(self.centralwidget)
        self.text_level.setGeometry(QtCore.QRect(70, 465, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.text_level.setFont(font)
        self.text_level.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_level.setObjectName("text_level")
        self.text_score = QtWidgets.QLabel(self.centralwidget)
        self.text_score.setGeometry(QtCore.QRect(70, 515, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.text_score.setFont(font)
        self.text_score.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_score.setObjectName("text_score")
        self.text_lives = QtWidgets.QLabel(self.centralwidget)
        self.text_lives.setGeometry(QtCore.QRect(500, 465, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.text_lives.setFont(font)
        self.text_lives.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_lives.setObjectName("text_lives")
        self.text_speed = QtWidgets.QLabel(self.centralwidget)
        self.text_speed.setGeometry(QtCore.QRect(500, 515, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.text_speed.setFont(font)
        self.text_speed.setStyleSheet("color: rgb(255, 255, 255);")
        self.text_speed.setObjectName("text_speed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuRules = QtWidgets.QMenu(self.menubar)
        self.menuRules.setObjectName("menuRules")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuRules.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Snake"))
        self.text_level.setText(_translate("MainWindow", "Level: 1"))
        self.text_score.setText(_translate("MainWindow", "Score: 0"))
        self.text_lives.setText(_translate("MainWindow", "Lives: 3"))
        self.text_speed.setText(_translate("MainWindow", "Speed: x1"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuRules.setTitle(_translate("MainWindow", "Rules"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
